baseURL = "https://www.theexpattech.com/"
languageCode = "en-us"
title = "The Expat Tech"
publishDir = "docs"

[taxonomies]
  category = "categories"
  tag      = "tags"
  author   = "authors"

[module]
  [[module.imports]]
    path = "github.com/dillonzq/LoveIt"

[menu]
  [[menu.main]]
    identifier = "aviation"
    name = "Aviation"
    url = "/aviation/"
    weight = 30

  [[menu.main]]
    identifier = "tech-tips"
    name = "Tech Tips"
    url = "/tech-tips/"
    weight = 40

  [[menu.main]]
    identifier = "digital-nomading"
    name = "Digital Nomading"
    url = "/digital-nomading/"
    weight = 50
    
  [[menu.main]]
    identifier = "living-in-mexico"
    name = "Living In Mexico"
    url = "/living-in-mexico/"
    weight = 60
  
  [[menu.main]]
    identifier = "misc"
    name = "Misc"
    url = "/misc/"
    weight = 70 

[params.header]
  desktopMode = "fixed"
  mobileMode  = "auto"

  [params.header.title]
    name = "The Expat Tech"
    type = "text"   # options: "text" or "img"
    url  = "/"      # clicking the title takes you home

[params.home.profile]
  enable = true

[params.home.posts]
  enable = true

[params.author]
  name = "ZDevilInside"
  link = "/about/"

[params]
  # Theme settings
  defaultTheme = "dark"   # options: "light", "dark", "auto"
  themeToggle = true      # show toggle button in header

[permalinks]
aviation = "/aviation/:slug/"
digital-nomading = "/digital-nomading/:slug/"
living-in-mexico = "/living-in-mexico/:slug/"
tech-tips = "/tech-tips/:slug/"
misc = "/misc/:slug/"
