baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'The Expat Tech'

[taxonomies]
  category = "categories"
  tag      = "tags"
  # remove or comment out "author = authors" since LoveIt uses global author params

[module]
  [[module.imports]]
    path = "github.com/dillonzq/LoveIt"

[menu]
  [[menu.main]]
    identifier = "aviation"
    name = "Aviation"
    url = "/posts/aviation/"
    weight = 30

  [[menu.main]]
    identifier = "tech-tips"
    name = "Tech Tips"
    url = "/posts/tech-tips/"
    weight = 40

  [[menu.main]]
    identifier = "digital-nomading"
    name = "Digital Nomading"
    url = "/posts/digital-nomading/"
    weight = 50
    
  [[menu.main]]
    identifier = "LivingInMexico"
    name = "Living In Mexico"
    url = "/posts/Living In Mexico/"
    weight = 60

[params.header]
  desktopMode = "fixed"
  mobileMode = "auto"

  [params.header.title]
    logo = ""                # optional logo path, e.g. "/images/logo.png"
    name = "The Expat Tech"  # upper-left corner site title
    pre = ""                 # remove demo icon
    post = ""                # optional text after the name
    typeit = false           # disable typewriter animation

[params.home.profile]
  enable = false

[params.home.posts]
  enable = false

[params.author]
  name = "ZDevilInside"
  link = "/about/"   # optional link to your About page or external profile
[params]
  defaultTheme = "dark"